<?php

drupal_add_js(drupal_get_path('module', 'user_list') .'/user_list.js');
drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyAtwq1zUmBanBSj6mp3UyI7SNjTC5dNjuc','external');

function user_list_user_presave(&$edit,$account, $category){
  	$ft = $edit["field_ft"]["und"][0]["value"];
	$in = $edit["field_in"]["und"][0]["value"];
	$height = floatval($ft.".".$in);
	$height_gen = "short";
	if($height >= 5.9){
		$height_gen = "tall";
	} else if($height >= 5.4 && $height < 5.9){
		$height_gen = "medium";
	}
	$edit["field_height_gen"]["und"][0]["value"] = $height_gen;
}
?>