<?php

drupal_add_js(drupal_get_path('module', 'user_list') .'/user_list.js');
drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyAtwq1zUmBanBSj6mp3UyI7SNjTC5dNjuc','external');

function user_list_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'user_list'),
    'template path' => drupal_get_path('module', 'user_list')
  );
}
/**
 * Impliments hook_theme()
 */
function user_list_theme($existing, $type, $theme, $path){
  return array(
    "preprocess functions"=>array("user_list_preprocess_views_view")	
  );
}

function user_list_preprocess_views_view(&$vars){
  $view = $vars["view"];
  if($view->name == "list_users"){
    $existing = array_key_exists("user_data",$GLOBALS) ? $GLOBALS["user_data"] : array();
    $result = array_merge($existing,$view->result);
    $GLOBALS["user_data"] = $result;
  }
}
?>